name: tima-bank-credit-risk

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - scikit-learn
  - scipy
  - xgboost
  - jupyter
  - ipykernel
  - papermill
  - python-dotenv
  - sqlalchemy
  - pyodbc
  - requests
  - pip
